### ISSUE TITLE
Call CompleteMessageAsync

### ISSUE THREAD

**Issue by forki** [jeffhollan/container-apps-dotnet-eventing#1]
https://github.com/jeffhollan/container-apps-dotnet-eventing/blob/437eb66a3b3d43d16d8327e62371e414267af2b2/service-bus/QueueProcessor.cs#L66

Shouldn't this call CompleteMessageAsync here?

**Comment by jeffhollan** [comment]
Optionally. Because I'm using the Service Bus Processor it will automatically call CompleteMessageAsync on completion of the handler. Or I can explicitly complete message somewhere in the method too. https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.servicebus-readme-pre#key-concepts

Note: if I want to manually complete you also need to setup the processor so it knows you will complete in your code
